# Generated by Django 3.2.9 on 2021-12-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('total_experience', models.IntegerField(null=True)),
                ('work_experience', models.JSONField(max_length=5000, null=True)),
            ],
        ),
    ]
