# Generated by Django 4.0 on 2021-12-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['total_experience']},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='candidate',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
